### ISSUE TITLE
Feature Requests: Remove update link to store.shopware.com

### ISSUE THREAD

**Issue by Tim-VL** [Werkstattl/OpenBlogware#6]
Now the store gives a pop-up every time a update is made on the original plugin. Please remove update link to store.shopware.com

**Comment by 7underlines** [comment]
I haven't seen this. Can you provide a screenshot where this happens?

**Comment by 7underlines** [comment]
I have a suspicion about what the issue could be. In some places, we are still using the same name as the original plugin. For example, here in the Shopware Update Wizard, it says 'SasBlogModule'. Of course, we can change that.

I would also change the database tables being used, because currently we are still using the same ones as the original plugin. However, this is a breaking change, and all content would need to be completely recreated. Would that be okay for you? It's better to do it now rather than later when the plugin has more users and more data.

![Bildschirmfoto vom 2024-09-15 05-50-03](https://github.com/user-attachments/assets/7abbbb16-9274-4081-b3a0-337ddfbd2991)

**Comment by 7underlines** [comment]
This should be fixed in v4.0.0.
Beware, this is a breaking release.
All content needs to be completely recreated.

**Comment by 7underlines** [comment]
Now it seems correct.

![Bildschirmfoto vom 2024-09-15 09-08-41](https://github.com/user-attachments/assets/f4080409-e016-4d2f-8f61-3e79e3803ade)

**Comment by Tim-VL** [comment]
Thanks, fixed now!
Keep up the good work.
